name:  🚀 Feature Request
description: Suggest a feature that you would like to see implemented
labels: ['enhancement']
body:
  - type: textarea
    attributes:
      label: What's the problem this feature will solve?
      description: >-
        What are you trying to do, that you are unable to achieve
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: >-
        Clear and concise description of what you want to happen and how it solves the
        problem described above
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: >-
        Add any other context, links, images, videos, etc. relevant to the feature request
