name: Build
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Checkout master
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Check format
        run: npm run check-format
